# Generated by Django 4.1.2 on 2022-11-05 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortenerproject', '0003_shortener'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortener',
            name='short_url',
            field=models.URLField(blank=True, max_length=20, unique=True),
        ),
    ]
