# Generated by Django 4.1.2 on 2022-11-09 07:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('urlshortenerproject', '0004_alter_shortener_short_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shortener',
            name='staff',
        ),
        migrations.AddField(
            model_name='shortener',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
