# Generated by Django 4.1.2 on 2022-11-12 08:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortenerproject', '0005_remove_shortener_staff_shortener_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='active_links',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='staff',
            name='remaining_links',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinLengthValidator(0)]),
        ),
    ]
