# Generated by Django 4.1.2 on 2022-11-12 09:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortenerproject', '0006_alter_staff_active_links_alter_staff_remaining_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='active_links',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='staff',
            name='remaining_links',
            field=models.PositiveIntegerField(default=10, validators=[django.core.validators.MinLengthValidator(0)]),
        ),
    ]
