# Generated by Django 4.1.2 on 2022-11-12 10:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortenerproject', '0008_alter_staff_active_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='active_links',
            field=models.PositiveIntegerField(default=0, max_length=10, validators=[django.core.validators.MaxLengthValidator(10)]),
        ),
    ]
