# Generated by Django 4.1.2 on 2022-11-12 11:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortenerproject', '0009_alter_staff_active_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='active_links',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
